export interface UNCountry {
  code: string;
  nameHe: string;
  nameEn: string;
  flag: string;
  langHe: string;
  langEn: string;
}

export const UN_COUNTRIES: UNCountry[] = [
  { code: 'AF', nameHe: 'אפגניסטן', nameEn: 'Afghanistan', flag: '🇦🇫', langHe: 'פשטו / דארי', langEn: 'Pashto / Dari' },
  { code: 'AL', nameHe: 'אלבניה', nameEn: 'Albania', flag: '🇦🇱', langHe: 'אלבנית', langEn: 'Albanian' },
  { code: 'DZ', nameHe: 'אלג׳יריה', nameEn: 'Algeria', flag: '🇩🇿', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'AD', nameHe: 'אנדורה', nameEn: 'Andorra', flag: '🇦🇩', langHe: 'קטלאנית', langEn: 'Catalan' },
  { code: 'AO', nameHe: 'אנגולה', nameEn: 'Angola', flag: '🇦🇴', langHe: 'פורטוגזית', langEn: 'Portuguese' },
  { code: 'AG', nameHe: 'אנטיגואה וברבודה', nameEn: 'Antigua and Barbuda', flag: '🇦🇬', langHe: 'אנגלית', langEn: 'English' },
  { code: 'AR', nameHe: 'ארגנטינה', nameEn: 'Argentina', flag: '🇦🇷', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'AM', nameHe: 'ארמניה', nameEn: 'Armenia', flag: '🇦🇲', langHe: 'ארמנית', langEn: 'Armenian' },
  { code: 'AU', nameHe: 'אוסטרליה', nameEn: 'Australia', flag: '🇦🇺', langHe: 'אנגלית', langEn: 'English' },
  { code: 'AT', nameHe: 'אוסטריה', nameEn: 'Austria', flag: '🇦🇹', langHe: 'גרמנית', langEn: 'German' },
  { code: 'AZ', nameHe: 'אזרבייג׳ן', nameEn: 'Azerbaijan', flag: '🇦🇿', langHe: 'אזרבייג׳נית', langEn: 'Azerbaijani' },
  { code: 'BS', nameHe: 'איי בהאמה', nameEn: 'Bahamas', flag: '🇧🇸', langHe: 'אנגלית', langEn: 'English' },
  { code: 'BH', nameHe: 'בחריין', nameEn: 'Bahrain', flag: '🇧🇭', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'BD', nameHe: 'בנגלדש', nameEn: 'Bangladesh', flag: '🇧🇩', langHe: 'בנגלית', langEn: 'Bengali' },
  { code: 'BB', nameHe: 'ברבדוס', nameEn: 'Barbados', flag: '🇧🇧', langHe: 'אנגלית', langEn: 'English' },
  { code: 'BY', nameHe: 'בלארוס', nameEn: 'Belarus', flag: '🇧🇾', langHe: 'בלארוסית / רוסית', langEn: 'Belarusian / Russian' },
  { code: 'BE', nameHe: 'בלגיה', nameEn: 'Belgium', flag: '🇧🇪', langHe: 'הולנדית / צרפתית / גרמנית', langEn: 'Dutch / French / German' },
  { code: 'BZ', nameHe: 'בליז', nameEn: 'Belize', flag: '🇧🇿', langHe: 'אנגלית', langEn: 'English' },
  { code: 'BJ', nameHe: 'בנין', nameEn: 'Benin', flag: '🇧🇯', langHe: 'צרפתית', langEn: 'French' },
  { code: 'BT', nameHe: 'בוטאן', nameEn: 'Bhutan', flag: '🇧🇹', langHe: 'דזונגקה', langEn: 'Dzongkha' },
  { code: 'BO', nameHe: 'בוליביה', nameEn: 'Bolivia', flag: '🇧🇴', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'BA', nameHe: 'בוסניה והרצגובינה', nameEn: 'Bosnia and Herzegovina', flag: '🇧🇦', langHe: 'בוסנית / קרואטית / סרבית', langEn: 'Bosnian / Croatian / Serbian' },
  { code: 'BW', nameHe: 'בוטסואנה', nameEn: 'Botswana', flag: '🇧🇼', langHe: 'אנגלית / סטסואנה', langEn: 'English / Setswana' },
  { code: 'BR', nameHe: 'ברזיל', nameEn: 'Brazil', flag: '🇧🇷', langHe: 'פורטוגזית', langEn: 'Portuguese' },
  { code: 'BN', nameHe: 'ברוניי', nameEn: 'Brunei', flag: '🇧🇳', langHe: 'מלאית', langEn: 'Malay' },
  { code: 'BG', nameHe: 'בולגריה', nameEn: 'Bulgaria', flag: '🇧🇬', langHe: 'בולגרית', langEn: 'Bulgarian' },
  { code: 'BF', nameHe: 'בורקינה פאסו', nameEn: 'Burkina Faso', flag: '🇧🇫', langHe: 'צרפתית', langEn: 'French' },
  { code: 'BI', nameHe: 'בורונדי', nameEn: 'Burundi', flag: '🇧🇮', langHe: 'קירונדי / צרפתית', langEn: 'Kirundi / French' },
  { code: 'CV', nameHe: 'קבו ורדה', nameEn: 'Cabo Verde', flag: '🇨🇻', langHe: 'פורטוגזית', langEn: 'Portuguese' },
  { code: 'KH', nameHe: 'קמבודיה', nameEn: 'Cambodia', flag: '🇰🇭', langHe: 'קמרית', langEn: 'Khmer' },
  { code: 'CM', nameHe: 'קמרון', nameEn: 'Cameroon', flag: '🇨🇲', langHe: 'צרפתית / אנגלית', langEn: 'French / English' },
  { code: 'CA', nameHe: 'קנדה', nameEn: 'Canada', flag: '🇨🇦', langHe: 'אנגלית / צרפתית', langEn: 'English / French' },
  { code: 'CF', nameHe: 'הרפובליקה המרכז אפריקאית', nameEn: 'Central African Republic', flag: '🇨🇫', langHe: 'סנגו / צרפתית', langEn: 'Sango / French' },
  { code: 'TD', nameHe: 'צ׳אד', nameEn: 'Chad', flag: '🇹🇩', langHe: 'צרפתית / ערבית', langEn: 'French / Arabic' },
  { code: 'CL', nameHe: 'צ׳ילה', nameEn: 'Chile', flag: '🇨🇱', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'CN', nameHe: 'סין', nameEn: 'China', flag: '🇨🇳', langHe: 'סינית מנדרינית', langEn: 'Mandarin Chinese' },
  { code: 'CO', nameHe: 'קולומביה', nameEn: 'Colombia', flag: '🇨🇴', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'KM', nameHe: 'קומורו', nameEn: 'Comoros', flag: '🇰🇲', langHe: 'קומורית / ערבית / צרפתית', langEn: 'Comorian / Arabic / French' },
  { code: 'CG', nameHe: 'קונגו', nameEn: 'Congo', flag: '🇨🇬', langHe: 'צרפתית', langEn: 'French' },
  { code: 'CR', nameHe: 'קוסטה ריקה', nameEn: 'Costa Rica', flag: '🇨🇷', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'HR', nameHe: 'קרואטיה', nameEn: 'Croatia', flag: '🇭🇷', langHe: 'קרואטית', langEn: 'Croatian' },
  { code: 'CU', nameHe: 'קובה', nameEn: 'Cuba', flag: '🇨🇺', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'CY', nameHe: 'קפריסין', nameEn: 'Cyprus', flag: '🇨🇾', langHe: 'יוונית / טורקית', langEn: 'Greek / Turkish' },
  { code: 'CZ', nameHe: 'צ׳כיה', nameEn: 'Czechia', flag: '🇨🇿', langHe: 'צ׳כית', langEn: 'Czech' },
  { code: 'CD', nameHe: 'הרפובליקה הדמוקרטית של קונגו', nameEn: 'DR Congo', flag: '🇨🇩', langHe: 'צרפתית', langEn: 'French' },
  { code: 'DK', nameHe: 'דנמרק', nameEn: 'Denmark', flag: '🇩🇰', langHe: 'דנית', langEn: 'Danish' },
  { code: 'DJ', nameHe: 'ג׳יבוטי', nameEn: 'Djibouti', flag: '🇩🇯', langHe: 'צרפתית / ערבית', langEn: 'French / Arabic' },
  { code: 'DM', nameHe: 'דומיניקה', nameEn: 'Dominica', flag: '🇩🇲', langHe: 'אנגלית', langEn: 'English' },
  { code: 'DO', nameHe: 'הרפובליקה הדומיניקנית', nameEn: 'Dominican Republic', flag: '🇩🇴', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'EC', nameHe: 'אקוודור', nameEn: 'Ecuador', flag: '🇪🇨', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'EG', nameHe: 'מצרים', nameEn: 'Egypt', flag: '🇪🇬', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'SV', nameHe: 'אל סלוודור', nameEn: 'El Salvador', flag: '🇸🇻', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'GQ', nameHe: 'גינאה המשוונית', nameEn: 'Equatorial Guinea', flag: '🇬🇶', langHe: 'ספרדית / צרפתית / פורטוגזית', langEn: 'Spanish / French / Portuguese' },
  { code: 'ER', nameHe: 'אריתריאה', nameEn: 'Eritrea', flag: '🇪🇷', langHe: 'טיגריניה / ערבית / אנגלית', langEn: 'Tigrinya / Arabic / English' },
  { code: 'EE', nameHe: 'אסטוניה', nameEn: 'Estonia', flag: '🇪🇪', langHe: 'אסטונית', langEn: 'Estonian' },
  { code: 'SZ', nameHe: 'אסווטיני', nameEn: 'Eswatini', flag: '🇸🇿', langHe: 'סוואזית / אנגלית', langEn: 'Swati / English' },
  { code: 'ET', nameHe: 'אתיופיה', nameEn: 'Ethiopia', flag: '🇪🇹', langHe: 'אמהרית', langEn: 'Amharic' },
  { code: 'FJ', nameHe: 'פיג׳י', nameEn: 'Fiji', flag: '🇫🇯', langHe: 'אנגלית / פיג׳ית / הינדית', langEn: 'English / Fijian / Hindi' },
  { code: 'FI', nameHe: 'פינלנד', nameEn: 'Finland', flag: '🇫🇮', langHe: 'פינית', langEn: 'Finnish' },
  { code: 'FR', nameHe: 'צרפת', nameEn: 'France', flag: '🇫🇷', langHe: 'צרפתית', langEn: 'French' },
  { code: 'GA', nameHe: 'גבון', nameEn: 'Gabon', flag: '🇬🇦', langHe: 'צרפתית', langEn: 'French' },
  { code: 'GM', nameHe: 'גמביה', nameEn: 'Gambia', flag: '🇬🇲', langHe: 'אנגלית', langEn: 'English' },
  { code: 'GE', nameHe: 'גאורגיה', nameEn: 'Georgia', flag: '🇬🇪', langHe: 'גאורגית', langEn: 'Georgian' },
  { code: 'DE', nameHe: 'גרמניה', nameEn: 'Germany', flag: '🇩🇪', langHe: 'גרמנית', langEn: 'German' },
  { code: 'GH', nameHe: 'גאנה', nameEn: 'Ghana', flag: '🇬🇭', langHe: 'אנגלית', langEn: 'English' },
  { code: 'GR', nameHe: 'יוון', nameEn: 'Greece', flag: '🇬🇷', langHe: 'יוונית', langEn: 'Greek' },
  { code: 'GD', nameHe: 'גרנדה', nameEn: 'Grenada', flag: '🇬🇩', langHe: 'אנגלית', langEn: 'English' },
  { code: 'GT', nameHe: 'גואטמלה', nameEn: 'Guatemala', flag: '🇬🇹', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'GN', nameHe: 'גינאה', nameEn: 'Guinea', flag: '🇬🇳', langHe: 'צרפתית', langEn: 'French' },
  { code: 'GW', nameHe: 'גינאה ביסאו', nameEn: 'Guinea-Bissau', flag: '🇬🇼', langHe: 'פורטוגזית', langEn: 'Portuguese' },
  { code: 'GY', nameHe: 'גיאנה', nameEn: 'Guyana', flag: '🇬🇾', langHe: 'אנגלית', langEn: 'English' },
  { code: 'HT', nameHe: 'האיטי', nameEn: 'Haiti', flag: '🇭🇹', langHe: 'קראולית / צרפתית', langEn: 'Haitian Creole / French' },
  { code: 'HN', nameHe: 'הונדורס', nameEn: 'Honduras', flag: '🇭🇳', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'HU', nameHe: 'הונגריה', nameEn: 'Hungary', flag: '🇭🇺', langHe: 'הונגרית', langEn: 'Hungarian' },
  { code: 'IS', nameHe: 'איסלנד', nameEn: 'Iceland', flag: '🇮🇸', langHe: 'איסלנדית', langEn: 'Icelandic' },
  { code: 'IN', nameHe: 'הודו', nameEn: 'India', flag: '🇮🇳', langHe: 'הינדי / אנגלית', langEn: 'Hindi / English' },
  { code: 'ID', nameHe: 'אינדונזיה', nameEn: 'Indonesia', flag: '🇮🇩', langHe: 'אינדונזית', langEn: 'Indonesian' },
  { code: 'IR', nameHe: 'איראן', nameEn: 'Iran', flag: '🇮🇷', langHe: 'פרסית', langEn: 'Persian' },
  { code: 'IQ', nameHe: 'עיראק', nameEn: 'Iraq', flag: '🇮🇶', langHe: 'ערבית / כורדית', langEn: 'Arabic / Kurdish' },
  { code: 'IE', nameHe: 'אירלנד', nameEn: 'Ireland', flag: '🇮🇪', langHe: 'אירית / אנגלית', langEn: 'Irish / English' },
  { code: 'IL', nameHe: 'ישראל', nameEn: 'Israel', flag: '🇮🇱', langHe: 'עברית / ערבית', langEn: 'Hebrew / Arabic' },
  { code: 'IT', nameHe: 'איטליה', nameEn: 'Italy', flag: '🇮🇹', langHe: 'איטלקית', langEn: 'Italian' },
  { code: 'JM', nameHe: 'ג׳מייקה', nameEn: 'Jamaica', flag: '🇯🇲', langHe: 'אנגלית', langEn: 'English' },
  { code: 'JP', nameHe: 'יפן', nameEn: 'Japan', flag: '🇯🇵', langHe: 'יפנית', langEn: 'Japanese' },
  { code: 'JO', nameHe: 'ירדן', nameEn: 'Jordan', flag: '🇯🇴', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'KZ', nameHe: 'קזחסטן', nameEn: 'Kazakhstan', flag: '🇰🇿', langHe: 'קזחית / רוסית', langEn: 'Kazakh / Russian' },
  { code: 'KE', nameHe: 'קניה', nameEn: 'Kenya', flag: '🇰🇪', langHe: 'סוואהילי / אנגלית', langEn: 'Swahili / English' },
  { code: 'KI', nameHe: 'קיריבטי', nameEn: 'Kiribati', flag: '🇰🇮', langHe: 'קיריבטית / אנגלית', langEn: 'Gilbertese / English' },
  { code: 'KP', nameHe: 'קוריאה הצפונית', nameEn: 'North Korea', flag: '🇰🇵', langHe: 'קוריאנית', langEn: 'Korean' },
  { code: 'KR', nameHe: 'קוריאה הדרומית', nameEn: 'South Korea', flag: '🇰🇷', langHe: 'קוריאנית', langEn: 'Korean' },
  { code: 'KW', nameHe: 'כווית', nameEn: 'Kuwait', flag: '🇰🇼', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'KG', nameHe: 'קירגיזסטן', nameEn: 'Kyrgyzstan', flag: '🇰🇬', langHe: 'קירגיזית / רוסית', langEn: 'Kyrgyz / Russian' },
  { code: 'LA', nameHe: 'לאוס', nameEn: 'Laos', flag: '🇱🇦', langHe: 'לאוטית', langEn: 'Lao' },
  { code: 'LV', nameHe: 'לטביה', nameEn: 'Latvia', flag: '🇱🇻', langHe: 'לטבית', langEn: 'Latvian' },
  { code: 'LB', nameHe: 'לבנון', nameEn: 'Lebanon', flag: '🇱🇧', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'LS', nameHe: 'לסוטו', nameEn: 'Lesotho', flag: '🇱🇸', langHe: 'ססוטו / אנגלית', langEn: 'Sesotho / English' },
  { code: 'LR', nameHe: 'ליבריה', nameEn: 'Liberia', flag: '🇱🇷', langHe: 'אנגלית', langEn: 'English' },
  { code: 'LY', nameHe: 'לוב', nameEn: 'Libya', flag: '🇱🇾', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'LI', nameHe: 'ליכטנשטיין', nameEn: 'Liechtenstein', flag: '🇱🇮', langHe: 'גרמנית', langEn: 'German' },
  { code: 'LT', nameHe: 'ליטא', nameEn: 'Lithuania', flag: '🇱🇹', langHe: 'ליטאית', langEn: 'Lithuanian' },
  { code: 'LU', nameHe: 'לוקסמבורג', nameEn: 'Luxembourg', flag: '🇱🇺', langHe: 'לוקסמבורגית / צרפתית / גרמנית', langEn: 'Luxembourgish / French / German' },
  { code: 'MG', nameHe: 'מדגסקר', nameEn: 'Madagascar', flag: '🇲🇬', langHe: 'מלגשית / צרפתית', langEn: 'Malagasy / French' },
  { code: 'MW', nameHe: 'מלאווי', nameEn: 'Malawi', flag: '🇲🇼', langHe: 'אנגלית / צ׳יצ׳ווה', langEn: 'English / Chichewa' },
  { code: 'MY', nameHe: 'מלזיה', nameEn: 'Malaysia', flag: '🇲🇾', langHe: 'מלאית', langEn: 'Malay' },
  { code: 'MV', nameHe: 'האיים המלדיביים', nameEn: 'Maldives', flag: '🇲🇻', langHe: 'דיבהי', langEn: 'Dhivehi' },
  { code: 'ML', nameHe: 'מאלי', nameEn: 'Mali', flag: '🇲🇱', langHe: 'צרפתית', langEn: 'French' },
  { code: 'MT', nameHe: 'מלטה', nameEn: 'Malta', flag: '🇲🇹', langHe: 'מלטזית / אנגלית', langEn: 'Maltese / English' },
  { code: 'MH', nameHe: 'איי מרשל', nameEn: 'Marshall Islands', flag: '🇲🇭', langHe: 'מרשלזית / אנגלית', langEn: 'Marshallese / English' },
  { code: 'MR', nameHe: 'מאוריטניה', nameEn: 'Mauritania', flag: '🇲🇷', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'MU', nameHe: 'מאוריציוס', nameEn: 'Mauritius', flag: '🇲🇺', langHe: 'אנגלית / צרפתית', langEn: 'English / French' },
  { code: 'MX', nameHe: 'מקסיקו', nameEn: 'Mexico', flag: '🇲🇽', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'FM', nameHe: 'מיקרונזיה', nameEn: 'Micronesia', flag: '🇫🇲', langHe: 'אנגלית', langEn: 'English' },
  { code: 'MD', nameHe: 'מולדובה', nameEn: 'Moldova', flag: '🇲🇩', langHe: 'רומנית', langEn: 'Romanian' },
  { code: 'MC', nameHe: 'מונקו', nameEn: 'Monaco', flag: '🇲🇨', langHe: 'צרפתית / מונגאסקית', langEn: 'French / Monégasque' },
  { code: 'MN', nameHe: 'מונגוליה', nameEn: 'Mongolia', flag: '🇲🇳', langHe: 'מונגולית', langEn: 'Mongolian' },
  { code: 'ME', nameHe: 'מונטנגרו', nameEn: 'Montenegro', flag: '🇲🇪', langHe: 'מונטנגרית', langEn: 'Montenegrin' },
  { code: 'MA', nameHe: 'מרוקו', nameEn: 'Morocco', flag: '🇲🇦', langHe: 'ערבית / ברברית', langEn: 'Arabic / Berber' },
  { code: 'MZ', nameHe: 'מוזמביק', nameEn: 'Mozambique', flag: '🇲🇿', langHe: 'פורטוגזית', langEn: 'Portuguese' },
  { code: 'MM', nameHe: 'מיאנמר', nameEn: 'Myanmar', flag: '🇲🇲', langHe: 'בורמזית', langEn: 'Burmese' },
  { code: 'NA', nameHe: 'נמיביה', nameEn: 'Namibia', flag: '🇳🇦', langHe: 'אנגלית / אפריקאנס', langEn: 'English / Afrikaans' },
  { code: 'NR', nameHe: 'נאורו', nameEn: 'Nauru', flag: '🇳🇷', langHe: 'נאורו-אנגלית', langEn: 'Nauruan / English' },
  { code: 'NP', nameHe: 'נפאל', nameEn: 'Nepal', flag: '🇳🇵', langHe: 'נפאלית', langEn: 'Nepali' },
  { code: 'NL', nameHe: 'הולנד', nameEn: 'Netherlands', flag: '🇳🇱', langHe: 'הולנדית', langEn: 'Dutch' },
  { code: 'NZ', nameHe: 'ניו זילנד', nameEn: 'New Zealand', flag: '🇳🇿', langHe: 'אנגלית / מאורית', langEn: 'English / Māori' },
  { code: 'NI', nameHe: 'ניקרגואה', nameEn: 'Nicaragua', flag: '🇳🇮', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'NE', nameHe: 'ניז׳ר', nameEn: 'Niger', flag: '🇳🇪', langHe: 'צרפתית', langEn: 'French' },
  { code: 'NG', nameHe: 'ניגריה', nameEn: 'Nigeria', flag: '🇳🇬', langHe: 'אנגלית', langEn: 'English' },
  { code: 'MK', nameHe: 'צפון מקדוניה', nameEn: 'North Macedonia', flag: '🇲🇰', langHe: 'מקדונית', langEn: 'Macedonian' },
  { code: 'NO', nameHe: 'נורווגיה', nameEn: 'Norway', flag: '🇳🇴', langHe: 'נורווגית', langEn: 'Norwegian' },
  { code: 'OM', nameHe: 'עומאן', nameEn: 'Oman', flag: '🇴🇲', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'PK', nameHe: 'פקיסטן', nameEn: 'Pakistan', flag: '🇵🇰', langHe: 'אורדו / אנגלית', langEn: 'Urdu / English' },
  { code: 'PW', nameHe: 'פלאו', nameEn: 'Palau', flag: '🇵🇼', langHe: 'פלאו-אנגלית', langEn: 'Palauan / English' },
  { code: 'PA', nameHe: 'פנמה', nameEn: 'Panama', flag: '🇵🇦', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'PG', nameHe: 'פפואה גינאה החדשה', nameEn: 'Papua New Guinea', flag: '🇵🇬', langHe: 'טוק פיסין / אנגלית', langEn: 'Tok Pisin / English' },
  { code: 'PY', nameHe: 'פרגוואי', nameEn: 'Paraguay', flag: '🇵🇾', langHe: 'ספרדית / גוארני', langEn: 'Spanish / Guaraní' },
  { code: 'PE', nameHe: 'פרו', nameEn: 'Peru', flag: '🇵🇪', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'PH', nameHe: 'פיליפינים', nameEn: 'Philippines', flag: '🇵🇭', langHe: 'פיליפינית / אנגלית', langEn: 'Filipino / English' },
  { code: 'PL', nameHe: 'פולין', nameEn: 'Poland', flag: '🇵🇱', langHe: 'פולנית', langEn: 'Polish' },
  { code: 'PT', nameHe: 'פורטוגל', nameEn: 'Portugal', flag: '🇵🇹', langHe: 'פורטוגזית', langEn: 'Portuguese' },
  { code: 'QA', nameHe: 'קטר', nameEn: 'Qatar', flag: '🇶🇦', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'RO', nameHe: 'רומניה', nameEn: 'Romania', flag: '🇷🇴', langHe: 'רומנית', langEn: 'Romanian' },
  { code: 'RU', nameHe: 'רוסיה', nameEn: 'Russia', flag: '🇷🇺', langHe: 'רוסית', langEn: 'Russian' },
  { code: 'RW', nameHe: 'רואנדה', nameEn: 'Rwanda', flag: '🇷🇼', langHe: 'קיניארואנדה / צרפתית / אנגלית', langEn: 'Kinyarwanda / French / English' },
  { code: 'KN', nameHe: 'סנט קיטס ונוויס', nameEn: 'Saint Kitts and Nevis', flag: '🇰🇳', langHe: 'אנגלית', langEn: 'English' },
  { code: 'LC', nameHe: 'סנט לושיה', nameEn: 'Saint Lucia', flag: '🇱🇨', langHe: 'אנגלית', langEn: 'English' },
  { code: 'VC', nameHe: 'סנט וינסנט והגרנדינים', nameEn: 'Saint Vincent', flag: '🇻🇨', langHe: 'אנגלית', langEn: 'English' },
  { code: 'WS', nameHe: 'סמואה', nameEn: 'Samoa', flag: '🇼🇸', langHe: 'סמואית / אנגלית', langEn: 'Samoan / English' },
  { code: 'SM', nameHe: 'סן מרינו', nameEn: 'San Marino', flag: '🇸🇲', langHe: 'איטלקית', langEn: 'Italian' },
  { code: 'ST', nameHe: 'סאו טומה ופרינסיפה', nameEn: 'Sao Tome and Principe', flag: '🇸🇹', langHe: 'פורטוגזית', langEn: 'Portuguese' },
  { code: 'SA', nameHe: 'ערב הסעודית', nameEn: 'Saudi Arabia', flag: '🇸🇦', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'SN', nameHe: 'סנגל', nameEn: 'Senegal', flag: '🇸🇳', langHe: 'צרפתית / וולוף', langEn: 'French / Wolof' },
  { code: 'RS', nameHe: 'סרביה', nameEn: 'Serbia', flag: '🇷🇸', langHe: 'סרבית', langEn: 'Serbian' },
  { code: 'SC', nameHe: 'סיישל', nameEn: 'Seychelles', flag: '🇸🇨', langHe: 'קראולית סיישלרית / אנגלית / צרפתית', langEn: 'Seychellois Creole / English / French' },
  { code: 'SL', nameHe: 'סיירה לאון', nameEn: 'Sierra Leone', flag: '🇸🇱', langHe: 'אנגלית', langEn: 'English' },
  { code: 'SG', nameHe: 'סינגפור', nameEn: 'Singapore', flag: '🇸🇬', langHe: 'אנגלית / מלאית / סינית / טמילית', langEn: 'English / Malay / Mandarin / Tamil' },
  { code: 'SK', nameHe: 'סלובקיה', nameEn: 'Slovakia', flag: '🇸🇰', langHe: 'סלובקית', langEn: 'Slovak' },
  { code: 'SI', nameHe: 'סלובניה', nameEn: 'Slovenia', flag: '🇸🇮', langHe: 'סלובנית', langEn: 'Slovenian' },
  { code: 'SB', nameHe: 'איי שלמה', nameEn: 'Solomon Islands', flag: '🇸🇧', langHe: 'אנגלית', langEn: 'English' },
  { code: 'SO', nameHe: 'סומליה', nameEn: 'Somalia', flag: '🇸🇴', langHe: 'סומלית / ערבית', langEn: 'Somali / Arabic' },
  { code: 'ZA', nameHe: 'דרום אפריקה', nameEn: 'South Africa', flag: '🇿🇦', langHe: 'אפריקאנס / אנגלית / זולו', langEn: 'Afrikaans / English / Zulu' },
  { code: 'SS', nameHe: 'דרום סודאן', nameEn: 'South Sudan', flag: '🇸🇸', langHe: 'אנגלית', langEn: 'English' },
  { code: 'ES', nameHe: 'ספרד', nameEn: 'Spain', flag: '🇪🇸', langHe: 'ספרדית / קטלאנית / גליסית', langEn: 'Spanish / Catalan / Galician' },
  { code: 'LK', nameHe: 'סרי לנקה', nameEn: 'Sri Lanka', flag: '🇱🇰', langHe: 'סינהאלה / טמילית', langEn: 'Sinhala / Tamil' },
  { code: 'SD', nameHe: 'סודאן', nameEn: 'Sudan', flag: '🇸🇩', langHe: 'ערבית / אנגלית', langEn: 'Arabic / English' },
  { code: 'SR', nameHe: 'סורינאם', nameEn: 'Suriname', flag: '🇸🇷', langHe: 'הולנדית', langEn: 'Dutch' },
  { code: 'SE', nameHe: 'שוודיה', nameEn: 'Sweden', flag: '🇸🇪', langHe: 'שוודית', langEn: 'Swedish' },
  { code: 'CH', nameHe: 'שוויץ', nameEn: 'Switzerland', flag: '🇨🇭', langHe: 'גרמנית / צרפתית / איטלקית', langEn: 'German / French / Italian' },
  { code: 'SY', nameHe: 'סוריה', nameEn: 'Syria', flag: '🇸🇾', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'TJ', nameHe: 'טג׳יקיסטן', nameEn: 'Tajikistan', flag: '🇹🇯', langHe: 'טג׳יקית', langEn: 'Tajik' },
  { code: 'TZ', nameHe: 'טנזניה', nameEn: 'Tanzania', flag: '🇹🇿', langHe: 'סוואהילי / אנגלית', langEn: 'Swahili / English' },
  { code: 'TH', nameHe: 'תאילנד', nameEn: 'Thailand', flag: '🇹🇭', langHe: 'תאית', langEn: 'Thai' },
  { code: 'TL', nameHe: 'מזרח טימור', nameEn: 'East Timor', flag: '🇹🇱', langHe: 'טטום / פורטוגזית', langEn: 'Tetum / Portuguese' },
  { code: 'TG', nameHe: 'טוגו', nameEn: 'Togo', flag: '🇹🇬', langHe: 'צרפתית', langEn: 'French' },
  { code: 'TO', nameHe: 'טונגה', nameEn: 'Tonga', flag: '🇹🇴', langHe: 'טונגאית / אנגלית', langEn: 'Tongan / English' },
  { code: 'TT', nameHe: 'טרינידד וטובגו', nameEn: 'Trinidad and Tobago', flag: '🇹🇹', langHe: 'אנגלית', langEn: 'English' },
  { code: 'TN', nameHe: 'תוניסיה', nameEn: 'Tunisia', flag: '🇹🇳', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'TR', nameHe: 'טורקיה', nameEn: 'Turkey', flag: '🇹🇷', langHe: 'טורקית', langEn: 'Turkish' },
  { code: 'TM', nameHe: 'טורקמניסטן', nameEn: 'Turkmenistan', flag: '🇹🇲', langHe: 'טורקמנית', langEn: 'Turkmen' },
  { code: 'TV', nameHe: 'טובאלו', nameEn: 'Tuvalu', flag: '🇹🇻', langHe: 'טובאלורית / אנגלית', langEn: 'Tuvaluan / English' },
  { code: 'UG', nameHe: 'אוגנדה', nameEn: 'Uganda', flag: '🇺🇬', langHe: 'אנגלית / סוואהילי', langEn: 'English / Swahili' },
  { code: 'UA', nameHe: 'אוקראינה', nameEn: 'Ukraine', flag: '🇺🇦', langHe: 'אוקראינית', langEn: 'Ukrainian' },
  { code: 'AE', nameHe: 'איחוד האמירויות הערביות', nameEn: 'United Arab Emirates', flag: '🇦🇪', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'GB', nameHe: 'בריטניה', nameEn: 'United Kingdom', flag: '🇬🇧', langHe: 'אנגלית', langEn: 'English' },
  { code: 'US', nameHe: 'ארצות הברית', nameEn: 'United States', flag: '🇺🇸', langHe: 'אנגלית', langEn: 'English' },
  { code: 'UY', nameHe: 'אורוגוואי', nameEn: 'Uruguay', flag: '🇺🇾', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'UZ', nameHe: 'אוזבקיסטן', nameEn: 'Uzbekistan', flag: '🇺🇿', langHe: 'אוזבקית', langEn: 'Uzbek' },
  { code: 'VU', nameHe: 'ונואטו', nameEn: 'Vanuatu', flag: '🇻🇺', langHe: 'ביסלמה / אנגלית / צרפתית', langEn: 'Bislama / English / French' },
  { code: 'VE', nameHe: 'ונצואלה', nameEn: 'Venezuela', flag: '🇻🇪', langHe: 'ספרדית', langEn: 'Spanish' },
  { code: 'VN', nameHe: 'וייטנאם', nameEn: 'Vietnam', flag: '🇻🇳', langHe: 'וייטנאמית', langEn: 'Vietnamese' },
  { code: 'YE', nameHe: 'תימן', nameEn: 'Yemen', flag: '🇾🇪', langHe: 'ערבית', langEn: 'Arabic' },
  { code: 'ZM', nameHe: 'זמביה', nameEn: 'Zambia', flag: '🇿🇲', langHe: 'אנגלית', langEn: 'English' },
  { code: 'ZW', nameHe: 'זימבבואה', nameEn: 'Zimbabwe', flag: '🇿🇼', langHe: 'שונה / נדבלה / אנגלית', langEn: 'Shona / Ndebele / English' }
];

export function getCountryByCode(code: string): UNCountry {
  return UN_COUNTRIES.find(c => c.code.toUpperCase() === code.toUpperCase()) || UN_COUNTRIES.find(c => c.code === 'IL')!;
}
